command_timeout = 300
add_newline = false

[git_metrics]
disabled = false

[nodejs]
disabled = true

[php]
disabled = true

[gcloud]
disabled = true

[character]
success_symbol = '[➜](bold green)'

[docker_context]
disabled = true

[time]
disabled = true
